// This file was auto-generated by ML.NET Model Builder. 

using System;
using AutoTraderML.Model;

namespace AutoTraderML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {


            float v = 6.375299E+17F;

            for (int i = 0; i < 10 ; i++)
            {
                // Create single instance of sample data from first line of dataset for model input
                ModelInput sampleData = new ModelInput()
                {
                    Col0 = v,
                };

                v+= 1000000;

                // Make a single prediction on the sample data and print results
                var predictionResult = ConsumeModel.Predict(sampleData);
                Console.WriteLine($"Col0: {sampleData.Col0}");
                Console.WriteLine($"\n\nPredicted Col1: {predictionResult.Score}\n\n");
            }

            Console.ReadKey();
        }
    }
}
